### ISSUE TITLE
Line 74 Entry Detector

### ISSUE THREAD

**Issue by DJfeen** [oliver-zehentleitner/raspberry-pi-entree-detector#2]
Once the program has entered the state of open and been open to long (600secs):
Line 74 causes the program to repetitively play the door is open chime followed by door open to long chime without delay.

i.e: once the condition has been met,
74    last_state = is_open_since, therefore = None
62    is_open = GPIO state
    then the first if statement is true:
                    door chime plays
   next loop the next elif statement is true:
                    door open to long chime plays

process repeats. door chime auto replays  2 sound files repetitively forever.

recommend resetting is_open_since to 0 or resetting a copy of the variable, perhaps copied in the first if statement. I say copy coz you don't want the same memory pointer with a different name.

**Comment by oliver-zehentleitner** [comment]
For the solution i coded this project we needed it exactly that way... you can submit a PR with enable/disable function of this behavior.

**Comment by oliver-zehentleitner** [comment]
Actually setting to `door_too_long_open_time_in_seconds = False` should already do this job:
https://github.com/oliver-zehentleitner/raspberry-pi-entree-detector/blob/master/entree-detector.py#L48
